blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/rizer001-Development/Discussions/discussions
    about: For general questions and conversations, please use GitHub Discussions.
  - name: 🎮 Discord
    url: https://dsc.gg/rizer001-Development
    about: Join our Discord server for real-time help and chat.
